### ISSUE TITLE
compiled driver not appear in DAW

### ISSUE THREAD

**Issue by sashsvamir** [biappi/SimpleVirusUSBMidiDriver#6]
After **BUILD SUCCESS**, `build/Release/SimpleVirusUSBMidi.plugin` was moved to `/Library/Audio/MIDI Driver` directory, but no luck to see new driver in list of midi devices in DAW.

**Comment by biappi-bux** [comment]
for it to show up, it is important that
- there is *no* official access driver installed -- if the access driver is not properly uninstalled, the two drivers might conflict because they try to claim the same device
- the machine has been rebooted -- it is the easiest way to reload all the relevant services

Also, i have personally tested the driver on Catalina (macOS 10.15) and Big Sur (macOS 11), there are some reports it works also in Monterey (macOS 12) but i haven't tested it myself yet.

**Comment by Diz-X** [comment]
It should work on Monterey, I am using it. Only thing is that you need to change "macOS Deployment Target" to 11.5. The IOMasterPort has been deprecated in macOS 12.0;

**Comment by sashsvamir** [comment]
Plugin was compiled on 10.13 High Sierra with xcode 9.4.1 with running just command `xcodebuild` in terminal. In output was `80 799 bytes` file size.
Then plugin was tested in both 10.13 High Sierra and 10.15 Catalina os x with previously removed `/Library/Audio/MIDI Drivers/Virus TI MIDI Driver.plugin` (just moved to bin).

**Comment by Diz-X** [comment]
SimpleVirusUSBMidi.plugin size of mine is 528KB (528.122 bytes), size may vary because of macOS Target and local signature.

**Comment by sashsvamir** [comment]
Now i tried compile plugin from xcode gui. just open and run build. As result 140kb file (more than before build running in cmd). But still no luck to appear in DAW =(
Should i add some sign to xcode build settings? Or some else things was missed?

**Comment by Diz-X** [comment]
The compiled version is automaticly signed to run locally on the comuter you compiled it on. So you cannot use a compiled version from another machine due to invalid certificate for that machine. That is the reason there is no compiled version available, as you need to sign up or the Apple Developer Program. 

I think the problem is not all original Virus drivers are deleted, you properly still have some things in the way. Maybe a good idea to create a shell script that removes all the original Virus drivers.

**Comment by sashsvamir** [comment]
@biappi-bux  > Also, i have personally tested the driver on Catalina (macOS 10.15)

Can you inform what exactly xcode version you had used for build driver on Catalina?

**Comment by sashsvamir** [comment]
Now i recompile driver on os x 10.15 with xcode 10.3 (build out size is `217kb`).
Then copied driver file to `/Library/Audio/MIDI Drivers` directory, also i had remove only native `Virus TI MIDI Driver.plugin` from same dir.
After reboot os x, new driver was recognized in system as follow devices:
`Access - Virus - Virus External Midi`
`Access - Virus - Virus External Synth`
Hardware with second driver `Access - Virus - Virus External Synth` works as expected!

**Comment by biappi** [comment]
@sashsvamir happy it's doing something for you!

also thanks @Diz-X for the help!
